### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by alt-vena** [killerstorm/cl-coin#1]
Hi, I would like to implement your library into a project of mine. Would you mind adding a license to this project? I can do it if you like, just let me know which one you want and I'll do a PR.

**Comment by killerstorm** [comment]
MIT license or similar would do.

BTW recently I found a way to do ECDSA in CL, at least the math is there. But getting it all together would take considerably time, and I'm not that interested anymore...

**Comment by alt-vena** [comment]
Ok ill add it when soon when I have time. For the ecc I have contributed to cl-ecc (https://github.com/krkhan/cl-ecc https://github.com/krkhan/cl-ecc) and added  the secp256k1 curve. It should be able to do bitcoin ecc - not secure or anything but it works. Im currently working on som bitcoin tools for cl and will put it on github when I feel there is something to show.
